name:                hpamixer
version:             0.1.0.0
github:              "TheDrawingCoding-Gamer/hpamixer"
license:             GPL-3.0-only
author:              "bulby"
maintainer:          "bulbyvr@gmail.com"
copyright:           "2021 BulbyVR"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/TheDrawingCoding-Gamer/hpamixer#readme>

dependencies:
- base >= 4.7 && < 5
extra-libraries: stdc++ pulse
include-dirs: ffi c/pamixer/src
cxx-options: 
  - -std=c++17
library:
  source-dirs: src
  cxx-sources: ffi/ffi.cpp c/pamixer/src/*.cc


executables:
  hpamixer-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - hpamixer

tests:
  hpamixer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hpamixer
